### ISSUE TITLE
convert scripts to python3

### ISSUE THREAD

**Issue by korobkin** [laristra/flecsph#75]
since python 2.7 support is going to be phased out, all python scripts in the repository need to be updated to python 3 standard

**Comment by hlim88** [comment]
Yes! all python scripts that I made, tov_solver, some converters, and viz script, are python3 compatible

**Comment by hlim88** [comment]
I checked and updated all python scripts. Now, everything works with python3.
I suggest that you call python3 modules as default. For example, grizzly should use python 3.6 if you call it.

For future script, please make python3 compatible script rather than 2.7. (Python 2.7 will not be supported after 2020. See this website https://pythonclock.org/)

If you find any errors, please open issue again
